version: '3.5'

x-environment-vars: &environment-vars
  DATABASE_URL: postgresql://open_event_user:opev_pass@postgres:5432/open_event
  ELASTICSEARCH_HOST: elastic:9200
  REDIS_URL: redis://redis:6379/0
  ADMIN_EMAIL: "@{ADMIN_EMAIL}"
  ADMIN_PASSWORD: "@{ADMIN_PASSWORD}"

x-defaults: &defaults
  build: .
  restart: unless-stopped
  environment:
    <<: *environment-vars
  depends_on:
    - postgres
    - redis
    - elastic
  links:
    - postgres:postgres
    - redis:redis
    - elastic:elastic
  volumes:
    - ./data/web:/open_event/static

services:

  postgres:
    image: postgres:10-alpine
    container_name: opev-postgres
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: open_event_user
      POSTGRES_PASSWORD: opev_pass
      POSTGRES_DB: open_event

  redis:
    image: redis:3-alpine
    container_name: opev-redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - rd:/var/lib/redis/data

  elastic:
    image: elasticsearch:5.6.12-alpine
    container_name: opev-elastic-search
    restart: unless-stopped
    environment:
        - discovery.type=single-node
    volumes:
        - es:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
        - 9300:9300

  web:
    <<: *defaults
    container_name: opev-web
    ports:
      - 8080:8080

  celery:
    <<: *defaults
    container_name: opev-celery
    environment:
      <<: *environment-vars
      DEPLOYMENT: celery
      C_FORCE_ROOT: "true"

volumes:
    pg:
    rd:
    es:
